//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingMySong.Models.mDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int idComment { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idSong { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> dateComment { get; set; }
    }
}
