//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingMySong.Models.mDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        public int idSubCategory { get; set; }
        public Nullable<int> idCate { get; set; }
        public string subCateName { get; set; }
        public string subCateIMG { get; set; }
    }
}
