CREATE DATABASE [SingMySong]
begin
EXEC [SingMySong].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SingMySong] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SingMySong] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SingMySong] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SingMySong] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SingMySong] SET ARITHABORT OFF 
GO
ALTER DATABASE [SingMySong] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SingMySong] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SingMySong] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SingMySong] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SingMySong] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SingMySong] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SingMySong] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SingMySong] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SingMySong] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SingMySong] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SingMySong] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SingMySong] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SingMySong] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SingMySong] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SingMySong] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SingMySong] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SingMySong] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SingMySong] SET RECOVERY FULL 
GO
ALTER DATABASE [SingMySong] SET  MULTI_USER 
GO
ALTER DATABASE [SingMySong] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SingMySong] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SingMySong] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SingMySong] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [SingMySong] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'SingMySong', N'ON'
GO
USE [SingMySong]
GO
/****** Object:  Table [dbo].[Album]    Script Date: 8/6/2019 8:17:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Album](
	[idAlbum] [int] IDENTITY(1,1) NOT NULL,
	[idCategory] [int] NULL,
	[idSubCategory] [int] NULL,
	[albumName] [nvarchar](50) NULL,
	[albumIMG] [nvarchar](100) NULL,
 CONSTRAINT [PK_Album] PRIMARY KEY CLUSTERED 
(
	[idAlbum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Category]    Script Date: 8/6/2019 8:17:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category](
	[idCategory] [int] IDENTITY(1,1) NOT NULL,
	[cateName] [nvarchar](50) NULL,
	[cateIMG] [nvarchar](50) NULL,
 CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED 
(
	[idCategory] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Comments]    Script Date: 8/6/2019 8:17:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comments](
	[idComment] [int] IDENTITY(1,1) NOT NULL,
	[idUser] [int] NULL,
	[idSong] [int] NULL,
	[comments] [text] NULL,
	[dateComment] [date] NULL,
 CONSTRAINT [PK_Comments] PRIMARY KEY CLUSTERED 
(
	[idComment] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[FeedBack]    Script Date: 8/6/2019 8:17:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FeedBack](
	[idFeedBack] [int] IDENTITY(1,1) NOT NULL,
	[idRate] [int] NULL,
	[idUser] [int] NULL,
	[nameFB] [nvarchar](50) NULL,
	[email] [nvarchar](50) NULL,
	[phone] [nvarchar](50) NULL,
	[question] [nvarchar](150) NULL,
	[dateFeedback] [date] NULL,
 CONSTRAINT [PK_FeedBack] PRIMARY KEY CLUSTERED 
(
	[idFeedBack] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Rate]    Script Date: 8/6/2019 8:17:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rate](
	[idRate] [int] IDENTITY(1,1) NOT NULL,
	[rateName] [nvarchar](50) NULL,
 CONSTRAINT [PK_Rate] PRIMARY KEY CLUSTERED 
(
	[idRate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Songs]    Script Date: 8/6/2019 8:17:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Songs](
	[idSong] [int] IDENTITY(1,1) NOT NULL,
	[idCate] [int] NULL,
	[idSubCate] [int] NULL,
	[idType] [int] NULL,
	[songName] [nvarchar](50) NULL,
	[singerName] [nvarchar](50) NULL,
	[fileSong] [nvarchar](255) NULL,
 CONSTRAINT [PK_Songs] PRIMARY KEY CLUSTERED 
(
	[idSong] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[SubCategory]    Script Date: 8/6/2019 8:17:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SubCategory](
	[idSubCategory] [int] IDENTITY(1,1) NOT NULL,
	[idCate] [int] NULL,
	[subCateName] [nvarchar](50) NULL,
	[subCateIMG] [nvarchar](100) NULL,
 CONSTRAINT [PK_SubCategory] PRIMARY KEY CLUSTERED 
(
	[idSubCategory] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Type]    Script Date: 8/6/2019 8:17:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Type](
	[idType] [int] IDENTITY(1,1) NOT NULL,
	[typeName] [nvarchar](50) NULL,
	[typeIMG] [nvarchar](100) NULL,
 CONSTRAINT [PK_Type] PRIMARY KEY CLUSTERED 
(
	[idType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Users]    Script Date: 8/6/2019 8:17:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[idUser] [int] IDENTITY(1,1) NOT NULL,
	[fullName] [nvarchar](50) NULL,
	[userName] [nvarchar](50) NULL,
	[passWord] [nvarchar](50) NULL,
	[city] [nvarchar](100) NULL,
	[phone] [nvarchar](50) NULL,
	[gender] [bit] NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[idUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
